import type { Ad, Colecao } from './types'

export const colecoes: Colecao[] = [
  { id: 'novos-ads',       nome: 'Novos Ads'       },
  { id: 'codigo-da-escala', nome: 'Código da Escala' },
]

export const adsIniciais: Ad[] = [
  {
    id: 'guia-05',
    titulo: 'Guia 5',
    nome: 'Especialista feito de otário',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: 'O especialista é feito de otário toda hora nesse mercado, né?\n\nOlha como é que geralmente você toca o seu negócio. Você se mata de produzir conteúdo, faz live até ficar rouco, entrega sua genialidade de graça no Instagram e espera que o algoritmo seja bondoso com você.\n\nO mercado quebra as suas pernas, te dá a muleta e ainda faz você agradecer por isso.',
    corpo: 'Em outras palavras: você cria um ativo valiosíssimo, valida um produto que transforma vidas, mas no final do lançamento... Cadê o lucro? Cadê a previsibilidade?\n\nMês que vem você tem que começar tudo do zero de novo. "Obrigado, Especialista! Valeu pelo conteúdo gratuito, agora vou comprar de quem tem um funil de vendas pronto."\n\nNão é possível que as pessoas não perceberam isso até agora. Na verdade, talvez você já tenha percebido, mas ainda não mudou.\n\nVocê ainda está só reagindo. Está trabalhando para "pagar o dia" de volta, vendendo a sua imagem e o seu tempo precioso.\n\nNa verdade, você deveria estar construindo o ativo que bota dinheiro no seu bolso todo santo dia. Um sistema onde você mantém o controle dentro de casa e não depende do seu humor ou da entrega do Instagram para vender.',
    cta: 'Então, se você quer reestruturar o seu modelo de negócio e começar a ganhar na proporção do resultado que você é capaz de gerar — em vez de viver de picos de faturamento que te deixam ansioso...\n\nEu quero te mostrar como você pode estruturar o "Código da Escala" e parar de jogar o jogo errado.\n\nPara isso, eu liberei alguns horários na agenda do meu time para avaliarem o seu modelo atual, entenderem o seu contexto e te ajudarem a romper esse teto onde você está travado.\n\nIndependente se você fatura 10, 50 ou 100 mil. Independente do seu nicho. A gente consegue te ajudar a colocar tração e previsibilidade.\n\nToca no botão aqui abaixo, faz sua inscrição e eu te espero lá.',
  },
  {
    id: 'guia-06',
    titulo: 'Guia 6',
    nome: 'Escravo do próprio lançamento',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: 'Toda semana um especialista me para e fala: "Luiz, eu não aguento mais depender de live pra vender e ficar morrendo de medo do meu lançamento oscilar". Eu respondo sempre a mesma coisa: você não precisa ser escravo do seu próprio lançamento.',
    corpo: 'O problema não é sua entrega ou seu conteúdo. O gargalo é que o seu modelo de negócio depende 100% da sua energia vital pra funcionar. No modelo que eu criei, você foca na sua genialidade enquanto o sistema roda.\n\nSem você precisar fazer mais outra live se não quiser, o faturamento entra, o lucro é real e a escala acontece.\n\nO Daniel, por exemplo, faturou R$313 mil em um único mês. Antes, pra chegar perto disso, a gente sabe o deserto que o cara tinha que atravessar. Estamos falando de um modelo que gera previsibilidade todo santo dia da semana, não só no "carrinho aberto".',
    cta: 'Se você já é um especialista ou mentor, já fatura no digital, mas quer parar de ser um trabalhador da sua empresa para virar um empresário de verdade... você precisa entender como o novo jogo funciona.\n\nClica no botão aqui embaixo e entenda como escalar seu negócio sem precisar aparecer todo santo dia no Instagram.',
  },
  {
    id: 'guia-07',
    titulo: 'Guia 7',
    nome: 'Nunca fiz lançamento sem live (Karine)',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: '"Eu nunca fiz lançamento sem live, isso não dá certo."\n"Eu não tenho tempo de gravar conteúdo todo dia."\n\nEssas foram as duas maiores travas da Karine antes de entrar na mentoria. Ela era costureira, trabalhava enquanto assistia às calls. Hoje ela fatura R$ 500 mil por lançamento e fechou 2024 com R$ 4 milhões no bolso.',
    corpo: 'O Daniel era meu gestor de tráfego, ganhava R$ 5 mil. Aplicou o modelo e no dezembro seguinte bateu R$ 313 mil em um único mês.\n\nO que eu construí não é uma "diquinha" de Instagram. É um sistema de lançamento contínuo que roda com comercial e funil de quiz. Você para de depender de estar de bom humor ou da entrega do orgânico para vender.\n\nA gente está falando de previsibilidade. De ter lucro antes mesmo da primeira live começar.',
    cta: 'Se você é especialista, já faz lançamentos, mas vive nessa corda bamba de um mês bom e um mês ruim, eu quero te mostrar o novo jogo.\n\nClica aqui abaixo, aplica para uma sessão estratégica e eu vou te mostrar como implementar esse modelo no seu cenário atual para você parar de ser um escravo da própria empresa.',
  },
  {
    id: 'guia-08',
    titulo: 'Guia 8',
    nome: 'Preso no modelo errado',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: 'Você não está estagnado, você só está preso no modelo errado.\n\nHoje existem especialistas faturando 100, 200, 500 mil reais por mês, mas que ainda são os maiores trabalhadores da própria empresa.\n\nVocê sabe ensinar, sabe atrair gente e tem um produto que transforma vidas. O problema não é o seu conteúdo.',
    corpo: 'O problema é que você está jogando o jogo do lançamento semanal que depende de você estar 100% do tempo ao vivo, com a energia lá no alto, rezando pro lead não esfriar.\n\nSe você já passou dos 6 dígitos mensais, mas sente que o seu lucro some no tráfego e que você não tem liberdade nenhuma porque tudo depende de você para funcionar, você precisa mudar o sistema operacional do seu negócio.\n\nEu criei um modelo onde a estrutura roda sem você precisar aparecer todo dia. Onde o comercial vende de segunda a segunda e o lucro entra antes mesmo da live começar.',
    cta: 'Clica aqui embaixo e aplica para uma sessão estratégica. Não é pitch de vendas, é uma direção real para quem cansou de ser escravo do próprio lançamento e quer escala com liberdade.',
  },
  {
    id: 'guia-09',
    titulo: 'Guia 9',
    nome: 'Não tenho tempo de fazer live',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: '"Mas eu não tenho tempo para ficar fazendo live todo semana." Essa é a maior trava de quase todo especialista que fatura alto mas vive escravo da própria operação. Deixa eu te falar: o jogo mudou.',
    corpo: 'Existe um processo estruturado onde o seu lançamento não depende do seu humor ou da sua presença ao vivo para vender. A gente implementou isso no final do ano passado e, logo nas primeiras semanas, o volume de vendas já estabilizou sem precisar de um único "carrinho aberto" tradicional.\n\nHoje, a operação roda com uma média de leads qualificados entrando todo santo dia, gerando lucro antes mesmo da entrega começar. São mais de R$ 80 mil recorrentes entrando no caixa, sem que o especialista precise ser um refém do Instagram.',
    cta: 'Se você já é um especialista, fatura no digital e quer entender como globalizar seu modelo para ter escala com liberdade, o caminho é esse. Eu vou te mostrar na prática como construir um time e um funil que vendem sem você.\n\nClica aqui e garante seu ingresso para o Código da Escala em Alphaville.',
  },
  {
    id: 'guia-10',
    titulo: 'Guia 10',
    nome: 'Efeito sanfona (Diálogo)',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'dialogo',
    status: 'nao-gravado',
    hook: 'Persona: Cara, não dá mais... eu não aguento mais esse efeito sanfona. Um mês a gente faz 100k, no outro não sobra nem pra pagar o tráfego. Parece que eu vivo pra postar story e rezar pra live dar gente.\n\nVoz da Razão: (Ri de canto) E tu acha mesmo que o problema é o algoritmo ou o lead que é ruim?',
    corpo: 'Persona: Pô, eu faço tudo! Gravo CPL, faço antecipação, abro o carrinho na segunda, fico 24 horas sem dormir no suporte... e quando termina, eu tô morto e o caixa tá vazio de novo. O especialista já tá de bico porque quer viajar e o negócio para se ele não aparecer.\n\nVoz da Razão: É, você não é um empresário, você é só o trabalhador mais caro da sua própria empresa. Tá escravo de um modelo que já morreu em 2023 e nem percebeu.\n\nPersona: Como assim "morreu"? Todo mundo ainda faz assim...\n\nVoz da Razão: Presta atenção: o jogo mudou. Quem tá colocando R$ 7 ou 8 dígitos no bolso hoje não depende de especialista estar de bom humor pra fazer live. A gente usa estrutura de Quiz e funil automático pra lucrar antes mesmo do lançamento começar. É venda todo dia, com comercial batendo meta enquanto você tá viajando ou cuidando da sua família.\n\nPersona: Ah, lá vem... mais uma "fórmula mágica" de automação que vai esfriar meu público, né?\n\nVoz da Razão: Nada disso. É estratégia pura. Eu apliquei isso na PLX, no Rafa Tarso, em mais de 128 lançamentos.',
    cta: 'Voz da Razão: Eu gravei uma aula curta, direto ao ponto, onde eu mostro os números reais desse novo jogo. Clica no botão aqui embaixo e dá uma olhada no que a gente tá fazendo agora em 2026.',
  },
  {
    id: 'guia-11',
    titulo: 'Guia 11',
    nome: 'Soco no estômago (Diálogo)',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'dialogo',
    status: 'nao-gravado',
    hook: 'Persona: Cara, não dá mais... esse lançamento foi um soco no estômago. Um mês a gente estoura, no outro parece que o lead esqueceu como clica no link. Eu não aguento mais essa oscilação.\n\nAmigo: E você ainda tá achando que o culpado é o algoritmo ou o "lead ruim", né? kkk',
    corpo: 'Persona: Mas eu faço tudo, pô! Gravo CPL, faço live de 2 horas, imploro pro especialista postar story todo dia... Se a gente não aparece uma tarde, o faturamento desaba. É um cansaço que não acaba.\n\nAmigo: Parabéns, você não é um empresário, você é o funcionário de luxo da sua própria agenda. Tá escravo do orgânico e nem percebeu.\n\nPersona: Como assim escravo? Eu invisto pesado em tráfego!\n\nAmigo: Presta atenção: o jogo mudou. Quem fatura alto hoje não depende de live milagrosa. Eles usam uma estrutura de quiz pra filtrar o lead e um comercial que trabalha todo dia. O lucro sai antes mesmo do lançamento começar. É modelo americano, direto no gerenciador enquanto você ouve seu louvor tranquilo.\n\nPersona: Ah, agora pronto. Mais uma "fórmula mágica" que só funciona pra quem vende curso de marketing?\n\nAmigo: Nada disso. Eu apliquei isso com costureira, com pastor que não tinha audiência, e até na operação do Marçal. É o que gerou R$13 milhões com um produto de 47 reais. É estrutura, não é mágica. O burro que executa ganha do inteligente que quer inventar.',
    cta: 'Amigo: Eu gravei uma aula curta, direto ao ponto, mostrando esse novo sistema de lançamento contínuo. Sem enrolação. Clica no "Saiba Mais" e dá uma olhada lá.',
  },
  {
    id: 'guia-12',
    titulo: 'Guia 12',
    nome: 'Fechei na raça às 22h (Diálogo)',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'dialogo',
    status: 'nao-gravado',
    hook: 'Persona: Cara, fiz tudo certo. Funil no ar, anúncio rodando, live gravada... e no final do mês ainda precisei ligar pra cliente na raça pra fechar o mês. Isso não faz sentido.\n\nAmigo: Espera. Você ligou pro cliente... e fechou?\n\nPersona: Fechei, mas não era pra ser assim. Todo mundo fala que o digital vende sozinho, que é só colocar o funil no ar e o dinheiro entra. Eu montei tudo isso pra não precisar falar com ninguém. E aí no fim sou eu no telefone às 22h.\n\nAmigo: Você montou um negócio digital pra não vender... e aí ficou surpreso que não vendeu. Faz sentido. kkk',
    corpo: 'Persona: Para de zoar. Você tá dizendo que eu preciso de vendedor? Isso não é escalar, isso é contratar problema.\n\nAmigo: Presta atenção. Desde 2019, em todo negócio que funcionou — drop, agência, lançamento — sempre teve time comercial. Não é sobre você ficar no telefone. É sobre ter alguém trabalhando o lead que não comprou, que não compareceu, que ficou em cima do muro. Esse cara some se você não falar com ele. E o time comercial não custa quase nada no início — você só paga comissão até ele vender. O custo entra junto com a receita.\n\nPersona: Mas e o funil? Pra que serve o funil se eu vou depender de vendedor do mesmo jeito?\n\nAmigo: O funil traz o lead. O comercial fecha o que o funil não fecha sozinho. Num lançamento de R$9 milhões que eu operei, o time comercial levantou quase R$3 milhões desse total. Sem eles, esse dinheiro ia embora. Funil e comercial não competem — um alimenta o outro.',
    cta: 'Amigo: Eu gravei uma aula mostrando como montar esse modelo do zero, com quiz, lançamento e comercial funcionando junto. Curto, sem enrolação. Clica no "Saiba Mais" e assiste lá.\n\nPersona: Vai ter aquela parte chata de "e aí, você quer mudar sua vida?" não vai...\nAmigo: Não. Já começa pelo conteúdo. Se você assistir e achar que não valeu, pode voltar aqui e me cobrar. Pode ir.',
  },
  {
    id: 'guia-13',
    titulo: 'Guia 13',
    nome: 'Emprego disfarçado de empresa (Diálogo)',
    colecao: 'novos-ads',
    tipo: 'anuncio',
    formato: 'dialogo',
    status: 'nao-gravado',
    hook: 'Persona: Cara... eu tô exausto. Se eu não apareço no story, não vende. Se eu não faço live, não vende. Minha empresa só funciona quando eu tô presente. Tirei 4 dias de folga e foi um desastre.\n\nAmigo: Você tem uma empresa ou tem um emprego disfarçado de empresa?\n\nPersona: Mas eu trabalho demais nisso, pô. Gravo conteúdo todo dia, apareço toda semana, tô sempre online... E mesmo assim, se fico dois dias sem aparecer, o faturamento despenca. Não tem lógica.\n\nAmigo: Tem lógica sim. Você construiu um negócio que depende de você aparecer. Não construiu uma empresa — construiu uma armadilha com o seu próprio rosto na porta.',
    corpo: 'Persona: Tá, mas como você resolve isso? Manda um clone meu trabalhar?\n\nAmigo: Quase isso. Existe um modelo onde o lançamento roda com uma live gravada de meses atrás. O quiz atrai o lead no automático, o comercial trabalha a lista todo dia, e você pode estar viajando que o negócio continua. Tenho um caso de um cara que a última live ao vivo foi há mais de um ano. Ele fechou o ano passado com mais de um milhão por mês.\n\nPersona: Ah, claro. E o lead não percebe que a live é gravada?\n\nAmigo: O lead que comprou ontem tem o mesmo nível de interesse de quem comprou há dois meses atrás quando a live foi gravada. Pra ele, é novo. É estrutura, não é enganação. Funciona com pastor, com costureira, com nicho de saúde. O modelo não depende do nicho — depende de você parar de achar que precisa aparecer pra vender.',
    cta: 'Amigo: Eu mostro como isso funciona numa aula curta, sem enrolação. Clica no "Saiba Mais" e assiste lá. Já começa direto no conteúdo.\n\nPersona: Vai ter aquela parte chata de pitch no final, né?\nAmigo: Não. Se você chegar no final e achar que não valeu, volta aqui e me xinga. Pode ir tranquilo.',
  },
  {
    id: 'vsl-upsell-diamond',
    titulo: 'VSL Upsell',
    nome: 'Upgrade Diamond — Jantar na Casa do Luiz',
    colecao: 'codigo-da-escala',
    tipo: 'vsl',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: 'Parabéns pela sua decisão. Você acabou de garantir sua cadeira no Código da Escala e eu te falo: essa foi a melhor decisão que você tomou para o seu negócio em 2026. O jogo mudou, e você decidiu não ficar para trás.\n\nMas agora, eu quero falar com quem quer caminhar no espírito e acessar uma frequência que não existe no palco.\n\nVocê já garantiu o seu ingresso padrão. Você vai ter o conteúdo, vai ver os números reais na tela e vai entender como funciona esse novo jogo. Mas existe um grupo ainda mais seleto. Um grupo que decidiu que não quer só assistir, quer proximidade.\n\nEu estou falando do Jantar exclusivo na minha casa.\n\nO transbordo que acontece fora das câmeras.',
    corpo: 'Presta atenção: você vai sair do evento e vai sentar na mesa comigo e com a turma que já está no campo de batalha, gerando resultado de verdade. É o momento de tirar sua dúvida cara a cara, de fazer o networking que você não faz em lugar nenhum e de estar em um ambiente de proximidade total.\n\nComo eu sempre digo: Eu sai de uma empresa com 10 milhões em dívidas para.... [COMPLETAR]. porque eu mudei minha frequência. O seu negócio é a mesma coisa. Estar na mesa certa muda o seu resultado.\n\nLá fora, esse upgrade custaria muito mais caro. Mas para você que acabou de entrar, eu vou fazer algo direto e sem enrolação, do jeito que eu gosto.',
    cta: 'Você vai poder fazer o seu upgrade para o Diamond agora por apenas 12x de R$ 166,67 ou R$ 2.000,00 à vista.\n\nÉ a sua única chance de acessar o ambiente mais exclusivo do Código da Escala. Eu não sei quantas vagas ainda restam enquanto você vê esse vídeo, porque são pouquíssimas cadeiras para manter a qualidade do jantar.\n\nSe você sente no coração que precisa desse acesso, clica no botão aqui embaixo.\n\nAutomaticamente, o sistema faz o upgrade e a cobrança vai para o seu cartão ou gera um novo PIX.\n\nNão deixa para depois.\n\nClica agora, garante seu lugar na mesa e a gente se vê em Alphaville, na minha casa.\n\nTamo junto.',
    observacoes: '⚠️ PENDENTE: Completar a frase "Eu sai de uma empresa com 10 milhões em dívidas para...." no corpo.',
  },
  {
    id: 'vsl-agradecimento-diamond',
    titulo: 'VSL Agradecimento',
    nome: 'Upgrade Diamond Confirmado',
    colecao: 'codigo-da-escala',
    tipo: 'vsl',
    formato: 'padrao',
    status: 'nao-gravado',
    hook: 'Parabéns. Agora você não é só mais um no evento, você faz parte do grupo que entendeu o que é transbordo de verdade.\n\nVocê acabou de tomar a decisão que vai separar o seu 2026 de tudo o que você já viveu até aqui.\n\nPresta atenção no que vai acontecer: você já tem sua cadeira no Código da Escala, mas agora você garantiu o seu lugar na mesa. Na minha mesa.',
    corpo: 'Tem coisa que a gente não fala no palco. Tem frequência que só se acessa no ambiente de casa, na descontração, na conversa olho no olho enquanto a gente janta.\n\nEu já estive do outro lado. Já tive 10 milhões em dívida, já tive o casamento destruído e já achei que o meu destino era ser o maior carvoeiro de Goiás. O que me tirou de lá não foi só técnica, foi acesso. Foi sentar com gente que estava em outra frequência.\n\nO seu upgrade Diamond foi confirmado.\n\nVocê vai receber no seu whatsapp todos os detalhes, o endereço da minha casa em Alphaville e as orientações para o nosso jantar exclusivo.\n\nLá, o jogo é outro. A gente vai abrir o jogo, tirar as dúvidas que travam a sua escala e, principalmente, conectar com gente que pensa grande. Como eu sempre digo: o burro que executa ganha do inteligente que só planeja. E você executou o movimento certo.',
    cta: 'Prepare o seu coração para esses dois dias. O evento vai ser forte, mas o nosso jantar vai ser o divisor de águas.\n\nA minha casa vai estar aberta para você.\n\nA gente se vê em Alphaville, no Código da Escala e depois, no jantar.\n\nTamo junto. Caminha no espírito.',
  },
]
